server:
  port: 9004
spring:
  application:
    name: recordserver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xc_learning
    username: root
    password: root
  redis:
    host: 127.0.0.1
    password: ok
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: FULL
myes:
  host: 127.0.0.1:9200