server:
  port: 8001
spring:
  application:
    name: gateway-server
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
zuul:
  routes:
    mycourseserver:
      path: /course/**
      serviceId: courseserver
    myuserserver:
      path: /user/**
      serviceId: userServer
